  
# Version format
version: 1.0.{build}

# Build worker image
image: Visual Studio 2019

# Build platform
platform: Any CPU

# Build Configuration
configuration: Debug

# MSBuild settings
build:
  project: T2\NewFinalTest2\FinalTest2.sln
  verbosity: quiet

# Execute script before build
before_build:
 - nuget restore T2\NewFinalTest2\FinalTest2.sln